//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zork2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoomStories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomStories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zork2.Resources.RoomStories", typeof(RoomStories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now in the beginning of the game from here you can move too the tree or to the house. Only the house is Locked so try to find the key that unlocks the house.
        /// </summary>
        internal static string Room1 {
            get {
                return ResourceManager.GetString("Room1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 10.
        /// </summary>
        internal static string Room10 {
            get {
                return ResourceManager.GetString("Room10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 2.
        /// </summary>
        internal static string Room2 {
            get {
                return ResourceManager.GetString("Room2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 3.
        /// </summary>
        internal static string Room3 {
            get {
                return ResourceManager.GetString("Room3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 4.
        /// </summary>
        internal static string Room4 {
            get {
                return ResourceManager.GetString("Room4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 5.
        /// </summary>
        internal static string Room5 {
            get {
                return ResourceManager.GetString("Room5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 6.
        /// </summary>
        internal static string Room6 {
            get {
                return ResourceManager.GetString("Room6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 7.
        /// </summary>
        internal static string Room7 {
            get {
                return ResourceManager.GetString("Room7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 8.
        /// </summary>
        internal static string Room8 {
            get {
                return ResourceManager.GetString("Room8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in room 9.
        /// </summary>
        internal static string Room9 {
            get {
                return ResourceManager.GetString("Room9", resourceCulture);
            }
        }
    }
}
